services:
  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 3
  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3
  website:
    image: ghcr.io/ikigai-systems/fundamento-standalone-website:latest
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresql/postgres
      - REDIS_URL=redis://redis
      - FORMULA_EVAL_MICROSERVICE_URL=http://formula:3001/formulas/eval
      - EDITOR=nano
    volumes:
      - credentials:/rails/config/credentials
    env_file:
      - env.standalone
    ports:
      - '3000:3000'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  jobs:
    image: ghcr.io/ikigai-systems/fundamento-standalone-website:latest
    command: bundle exec good_job start
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresql/postgres
      - REDIS_URL=redis://redis
      - FORMULA_EVAL_MICROSERVICE_URL=http://formula:3001/formulas/eval
      - EDITOR=nano
    volumes:
      - credentials:/rails/config/credentials
    env_file:
      - env.standalone
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  formula:
    image: ghcr.io/ikigai-systems/fundamento-standalone-formula:latest
    environment:
      FUNDAMENTO_BASE_URL: http://rails:3000
    env_file:
      - env.standalone
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres:
  credentials:
